Add -q option to anyframe-action-execute

diff --git a/anyframe-functions/actions/anyframe-action-execute b/anyframe-functions/actions/anyframe-action-execute
--- a/anyframe-functions/actions/anyframe-action-execute
+++ b/anyframe-functions/actions/anyframe-action-execute
@@ -1,3 +1,8 @@
+# anyframe-action-execute [-q|-Q]
+# Options
+# -q : quote special characters in the resulting words with backslashes
+# -Q : not quote special characters with backslashes [Default]
+
 function _anyframe-action-execute()
 {
   if zle; then
@@ -10,13 +15,37 @@ function _anyframe-action-execute()
   fi
 }
 
+local quote_item="0"
+local option OPTARG OPTIND
+while getopts ':q' option; do
+  case $option in
+  q)
+    quote_item="1"
+    ;;
+  Q)
+    quote_item="0"
+    ;;
+  *)
+    echo "$0: invalid option -- $OPTARG" 1>&2
+    return 1
+    ;;
+  esac
+done
+shift $((OPTIND - 1))
+
 local selected_items
 selected_items="$(cat)"
 if [[ -z "$selected_items" ]]; then
   return 1
 fi
 
-_anyframe-action-execute "$@" "${(f)selected_items}"
+if [[ "$quote_item" == "1" ]]; then
+  # (q) : Quote characters that are special to the shell in the resulting words with backslashes
+  _anyframe-action-execute "${(q)@}" "${(fq)selected_items}"
+else
+  _anyframe-action-execute "$@" "${(f)selected_items}"
+fi
+
 
 # Local Variables:
 # mode: Shell-Script
